Use  a auto increment unique identity to Mysql InnoDB PRIMARY KEY
apache/shardingsphere-elasticjob pull request #1890
Opened 2021-05-08 10:36 UTC by skaic

Fixes #1818.

2021-05-15 01:49 UTC, TeslaCN requested changes
Hi @skaic 
Thanks for your contribution!
I've noticed that some `ResultSet` in `org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorage` uses column index to retrieve data. If columns' order changed, those logic may be impacted. Could you have a look?

2021-05-17 12:26 UTC, skaic commented
Thanks for your hint

2021-05-17 12:37 UTC, skaic commented
hey @TeslaCN 
Thanks for your review and hint. 
I found the problem like you said. So, I add a test in `org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorageMySQLTest`  and fix the bug.

2021-05-18 15:03 UTC, TeslaCN requested changes

2021-05-18 15:03 UTC, TeslaCN commented on pom.xml
> +        <slf4j.version>1.7.25</slf4j.version>
Could you please keep the original version?

2021-05-18 15:03 UTC, TeslaCN commented on elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorage.java
> +                    JobStatusTraceEvent jobStatusTraceEvent = new JobStatusTraceEvent(
Could you please keep the original formats?

2021-05-18 15:03 UTC, TeslaCN commented on elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/pom.xml
> +            <artifactId>slf4j-api</artifactId>
Is it necessary to declare this dependency here?

2021-05-19 02:03 UTC, skaic commented on pom.xml
> +        <slf4j.version>1.7.25</slf4j.version>
i can't， because mariaDB4j  dependent slf4j to 1.7.20 version

2021-05-19 02:04 UTC, skaic commented on elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorage.java
> +                    JobStatusTraceEvent jobStatusTraceEvent = new JobStatusTraceEvent(
ok，I roll back the code.

2021-05-19 02:08 UTC, skaic commented on elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/pom.xml
> +            <artifactId>slf4j-api</artifactId>
No neet，I roll back the code.

2021-05-22 22:43 UTC, TeslaCN commented
Hi @skaic 
It seems the test case depends on a SSL library, could you have a look? https://github.com/apache/shardingsphere-elasticjob/pull/1890/checks?check_run_id=2647644568#step:4:3457

2021-05-23 15:18 UTC, TeslaCN commented
Hi @skaic 
Is there any options like `useSSL=false` can be configured in the test cases? There is no need to modify GitHub Action.

2021-05-23 16:12 UTC, skaic commented
> Hi @skaic
> Is there any options like `useSSL=false` can be configured in the test cases? There is no need to modify GitHub Action.

This is a difficult problem, look here  https://github.com/vorburger/MariaDB4j/issues/48
I don't have any good ideas.  :(

2021-05-24 06:53 UTC, skaic commented
I commit a temporary fix，but I think it not a good idea.  @TeslaCN

2021-05-26 16:11 UTC, TeslaCN commented
Hi @skaic 
I've checked out your branch and try `mvn install` on my MacBook and it failed. Maybe we should ignore this test until we found a better solution.

2021-05-27 01:48 UTC, skaic commented
> Hi @skaic
> I've checked out your branch and try `mvn install` on my MacBook and it failed. Maybe we should ignore this test until we found a better solution.

ok, I commit it.

2021-05-27 02:53 UTC, skaic commented
implement in a new branch

2021-05-27 02:53 UTC, closed without merging