Support timeout job
apache/shardingsphere-elasticjob pull request #1923
Opened 2021-07-07 07:50 UTC by sunkai-cai

Fixes #1464

Changes proposed in this pull request:
- add timeout of JobConfiguration
- support timeout for ElasticJobExecutor

2023-09-05 13:53 UTC, linghengqian reviewed
- Not sure if I'm asking too late. Should this PR add documentation?

2023-09-12 18:52 UTC, linghengqian requested changes
- I rebase the relevant branch, but it seems that some unit tests timeout.

2023-10-11 10:01 UTC, sunkai-cai commented
Maybe this is not a good design。 We need redesign it if we need the timeout features。

2026-01-31 10:09 UTC, RaigorJiang commented
This PR has been inactive for a long time, and I will close it.
Please submit a new one if needed, thank you!

2026-01-31 10:09 UTC, closed without merging