update `elasticjob.preferred.network.ip` docs
apache/shardingsphere-elasticjob pull request #1941
Opened 2021-07-24 03:50 UTC by sunkai-cai

update docs.

Changes proposed in this pull request:
- add `elasticjob.preferred.network.ip`  docs

2021-07-24 06:32 UTC, TeslaCN requested changes
The documents didn't clarify it supports regex.

2021-07-25 12:59 UTC, Technoboy- approved these changes
LGTM

2021-07-25 12:59 UTC, Technoboy- commented
@TeslaCN Please help to review.

2021-07-27 10:20 UTC, TeslaCN approved these changes

2021-07-27 10:20 UTC, merged