fix issue[2122] use unbounded thread pool to avoid watch lost
apache/shardingsphere-elasticjob pull request #2124
Opened 2022-09-24 08:56 UTC by xlcn

Fixes #2122 .

Changes proposed in this pull request:
- use unbounded thread pool to avoid watch lost
-
-

2022-09-27 14:03 UTC, TeslaCN requested changes
Is it possible that events will be processed concurrently after using the unbounded thread pool?
I'm not sure the impact of changing the basic test class.

2022-09-28 14:08 UTC, xlcn commented
> Is it possible that events will be processed concurrently after using the unbounded thread pool? I'm not sure the impact of changing the basic test class.

yes, should be processed concurrently, I'll try to find the reason.

2022-10-11 03:43 UTC, zhaojinchao95 commented on elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
> +        // ReflectionUtils.setFieldValue(JobRegistry.getInstance(), "instance", null);
@xlcn Hi, why adjustment here?

2022-10-11 03:43 UTC, zhaojinchao95 commented on elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/enable/EnabledJobIntegrateTest.java
> +        // assertTrue(getLeaderService().isLeaderUntilBlock());
@xlcn Hi, why adjustment here?

2022-10-11 03:49 UTC, zhaojinchao95 commented on elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/job/DetailedFooJob.java
> +        System.out.println(Thread.currentThread().getName() + " foo execute " + shardingContext);
Please remove this line.

2022-10-31 03:51 UTC, TeslaCN commented
We have avoided possibly endless loop in https://github.com/apache/shardingsphere-elasticjob/pull/2132. I'm closing this for now.

2022-10-31 03:51 UTC, closed without merging